### ISSUE TITLE
Allow the user to override the value of the `buildkite.version` file, maybe via an environment variable?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/external-buildkite-buildkite-plugin#12]
Suppose that I go to Buildkite, select a pipeline (e.g. `julia-release-1.6`), and click the "New Build" button. The dialog box that pops up includes an "Environment Variables" section in which I can specify custom environment variables as a list of key-value pairs.

Perhaps we can use this as a method for running builds with a specific `buildkite.version`.

For example, suppose that the `release-1.6` branch of the `JuliaLang/julia` repository has a `buildkite.version` file with the following contents:
```
buildkite-1.6
```

This tells the `JuliaCI/external-buildkite` plugin that we should use the `buildkite-1.6` branch of the `JuliaCI/julia-buildkite` repository.

Suppose that we instead want to make a build of the `release-1.6` branch of Julia, but instead of using the `buildkite-1.6` Buildkite configuration, we want to specify a custom commit from the `JuliaCI/julia-buildkite` repository.

Perhaps we can have an environment variable that the user can use to provide the custom Buildkite commit that they want to use. And if this environment variable is set (and nonempty), we ignore the `buildkite.version` file and instead use the commit specified in the environment variable.

I'm not sure what the best user interface is here, but some way of achieving this feature would be useful.

**Comment by DilumAluthge** [comment]
Hmmmm. Do we actually need this feature? We can accomplish the same functionality by doing the following:
1. Make a new branch `dpa/my-branch` from the `release-1.6` branch.
2. Push a new commit to the `dpa/my-branch` branch that edits the contents of the `buildkite.version` file so that the file contains the desired commit hash.
3. Click the "New Build" button and put `dpa/my-branch` in the "Branch" box.

So we can already accomplish the same functionality. But would it be easier/more convenient to be able to do this with an environment variable? Then you wouldn't have to make the branch and make a new commit.

**Comment by staticfloat** [comment]
Yeah, I'm happier with us just doing this by branching and adding commits.  :)

**Comment by DilumAluthge** [comment]
#21 fixes this very nicely by allowing the user to override this value by setting the appropriate Buildkite agent metadata before the plugin is run.
