### ISSUE TITLE
Why special-case first job?

### ISSUE THREAD

**Issue by staticfloat** [JuliaCI/external-buildkite-buildkite-plugin#18]
I don't quite understand why we special-case the first job?

**Comment by DilumAluthge** [comment]
It's to try to prevent https://github.com/JuliaCI/external-buildkite-buildkite-plugin/issues/13

I think we can make the user interface a bit cleaner though. For example, I don't think we actually need to have an explicit `this_is_first_job` input.

**Comment by DilumAluthge** [comment]
Closing in favor of #19
