### ISSUE TITLE
Use Buildkite agent metadata?

### ISSUE THREAD

**Issue by DilumAluthge** [JuliaCI/external-buildkite-buildkite-plugin#19]
> We can work around this by having the first job set a [buildkite metadata value](https://buildkite.com/docs/agent/v3/cli-meta-data). E.g. we can do something like:

> ```
> METADATA_KEY="external-buildkite-${REPO_URL_HASH}-${EXTERNAL_BRANCH_NAME}"
> CONCRETE_EXTERNAL_GITSHA="$(buildkite-agent meta-data get "${METADATA_KEY}" "")"
> if [[ -z "${CONCRETE_EXTERNAL_GITSHA}" ]]; then
>     CONCRETE_EXTERNAL_GITSHA="$(do_git_fetch "${REPO_URL}")"
>     buildkite-agent meta-data set "${METADATA_KEY}" "${CONCRETE_EXTERNAL_GITSHA}"
> else
>     do_git_checkout "${REPO_URL}" "${CONCRETE_EXTERNAL_GITSHA}"
> fi
> ```

_Originally posted by @staticfloat in https://github.com/JuliaCI/external-buildkite-buildkite-plugin/issues/13#issuecomment-970520702_

**Comment by DilumAluthge** [comment]
@staticfloat

1. How do we generate `REPO_URL_HASH`?
2. What is `EXTERNAL_BRANCH_NAME` here?

**Comment by DilumAluthge** [comment]
Oh, I think `EXTERNAL_BRANCH_NAME` is presumably the contents of the `buildkite.version` file. It might be a branch name, a tag name, or a commit hash.

**Comment by DilumAluthge** [comment]
Also, what is the advantage of using metadata instead of just environment variable interpolation?

BTW, we can get rid of the `this_is_first_job` stuff without needing to use metadata.

**Comment by staticfloat** [comment]
> Also, what is the advantage of using metadata instead of just environment variable interpolation?

metadata is shared across all jobs, whereas environment variables are not.

**Comment by DilumAluthge** [comment]
> How do we generate REPO_URL_HASH

@staticfloat Could you post a code snippet for computing this hash?

**Comment by DilumAluthge** [comment]
> > Also, what is the advantage of using metadata instead of just environment variable interpolation?
> 
> metadata is shared across all jobs, whereas environment variables are not.

Sure, but what I'm getting at is that if we use environment variable interpolation, we can achieve the same goal (synchronize the commit across all jobs) without having to add another moving part (the Buildkite agent metadata).

E.g. when we have a section like this:
```steps:
  - plugins:
    - JuliaCI/external-buildkite#v1.0:
        version: '${BUILDKITE_PLUGIN_EXTERNAL_BUILDKITE_VERSION?}'
        external_repo: '${BUILDKITE_PLUGIN_EXTERNAL_BUILDKITE_EXTERNAL_REPO?}'
        folder: '${BUILDKITE_PLUGIN_EXTERNAL_BUILDKITE_FOLDER?}'
```

The job that launches those pipelines will have those environment variables set, because the plugin sets those automatically at the end of the job. And then they get interpolated by Buildkite. So the propagation happens "automatically" every time we launch new pipelines.
